apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: t4zds4t0o-dotnet-basic
  janus-idp.io/tekton: t4zds4t0o-dotnet-basic
  backstage.io/kubernetes-id: t4zds4t0o-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: t4zds4t0o-dotnet-basic
resources:
- deployment.yaml
- route.yaml
- service.yaml
